version: '3'
services:

  fdk-model-publisher:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/fdk-model-publisher:test
    ports:
      - "8080:8080"
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
      - RABBIT_HOST=rabbitmq
      - FDK_DATASERVICE_HARVESTER=https://dataservices.staging.fellesdatakatalog.digdir.no
      - FDK_MODEL_PUBLISHER_URI=https://fdk-model-publisher.fellesdatakatalog.no
    depends_on:
      - fdk-publishers-cache
      - rabbitmq

  fdk-publishers-cache:
    image: redis:latest
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
