[tool.poetry]
name = "fdk-model-publisher"
version = "0.1.0"
description = "Transforms models included in dataservice-descriptions to modelldcat-ap-no compliant models and expose the collection"
authors = ["Nils Ove Tendenes <nils.ove@tendenes.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/Informasjonsforvaltning/fdk-model-publisher"
repository = "https://github.com/Informasjonsforvaltning/fdk-model-publisher"
classifiers=[
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]
[tool.poetry.dependencies]
python = "^3.8"
gunicorn = "^20.0.4"
python-dotenv = "^0.14.0"
modelldcatnotordf = "0.0.3"
datacatalogtordf = "^1.2.0"
fdk-rdf-parser = "0.2.1"
aiohttp = "^3.7.2"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
coverage = {extras = ["toml"], version = "^5.3"}
pytest-dotenv = "^0.5.2"
pytest-docker = "^0.10.1"
pytest-cov = "^2.10.1"
docker-compose = "^1.27.4"
black = "^20.8b1"
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
pep8-naming = "^0.11.1"
safety = "^1.9.0"
mypy = "^0.790"
flake8-annotations = "^2.4.1"
codecov = "^2.1.10"
requests-mock = "^1.8.0"
pytest-mock = "^3.3.1"
pytest-aiohttp = "^0.3.0"
aioresponses = "^0.7.1"
nox = "^2020.8.22"
nox_poetry = "^0.5.0"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = false
source = ["fdk_model_publisher"]
omit = ["*gunicorn_config.py"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
