name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy to production environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Install dependencies
        run: |
          pip install poetry==1.1.3
          pip install nox==2020.8.22
          pip install nox-poetry==0.6.0
          pip install virtualenv==20.2.1

      - name: Run tests with nox
        run: nox

      - name: Build Docker image with GitHub commit sha and latest tag
        run: docker build . -t eu.gcr.io/digdir-fdk-infra/fdk-model-publisher:$GITHUB_SHA -t eu.gcr.io/digdir-fdk-infra/fdk-model-publisher:latest

      - name: Publish Docker image to Google Cloud
        run: docker -- push eu.gcr.io/digdir-fdk-infra/fdk-model-publisher

      - name: Apply Helm template
        run: |
          helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
          helm fetch --untar --untardir ./helm fdk/fdk-model-publisher
          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/fdk-model-publisher:$GITHUB_SHA" -f ./helm/fdk-model-publisher/values/prod.yaml ./helm/fdk-model-publisher/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
          project_id: digdir-fdk-prod
          location_zone: europe-north1-a
          cluster_name: digdir-fdk-prod

      - name: Deploy to production
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: fdk-model-publisher | Environment: prod'
          fields: commit,author,workflow,message
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: Trigger deploy to demo
        uses: peter-evans/repository-dispatch@master
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          event-type: deploy-demo
          client-payload: '{"sha": "${{ github.sha }}"}'
